builds:
- id: worker
  dir: cmd/worker  # default is .
  # main: .
  env:
  - GOPRIVATE=*.vmware.com
  flags:
  - -tags
  - netgo
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.buildCommit={{.Env.KO_COMMIT}}
  - -X main.buildTag={{.Env.KO_TAG}}
- id: cli
  dir: cmd/preemptctl  # default is .
  # main: .
  env:
    - GOPRIVATE=*.vmware.com
  flags:
    - -tags
    - netgo
  ldflags:
    - -s -w
    - -extldflags "-static"
    - -X github.com/embano1/vsphere-preemption/cli.buildCommit={{.Env.KO_COMMIT}}
    - -X github.com/embano1/vsphere-preemption/cli.buildTag={{.Env.KO_TAG}}
